version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    command: ["sh", "-c", "npx prisma migrate dev && npm run start:dev"]
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres-data:
